admin_role: administrator
anonymous: Anonymous
verify_mail: '1'
notify:
  cancel_confirm: '1'
  password_reset: '1'
  status_activated: '1'
  status_blocked: '0'
  status_cancelled: '0'
  register_admin_created: '1'
  register_no_approval_required: '1'
  register_pending_approval: '1'
  status_canceled: '0'
register: admin_only
signatures: '0'
cancel_method: user_cancel_block
password_reset_timeout: '86400'
password_strength: '1'
langcode: en
